# -*- coding: utf-8 -*-
"""Introduction to Tableau and Data  Visualization| Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjiAAuQ9YbQy-LhhcI7Qg4kp72eGxcJK

Assignment Code: DA-AG-014
Introduction to Tableau and Data Visualization | Assignment
Question 1: What is Tableau? Explain its importance in Business Intelligence and how it helps in data-driven decision-making.
Answer:

Tableau is a powerful Business Intelligence (BI) and data visualization tool used to analyze, visualize, and share data in the form of interactive dashboards and reports.

Importance in Business Intelligence:
Converts raw data into meaningful insights
Helps organizations make data-driven decisions
Supports real-time analytics
Connects with multiple data sources
Simplifies complex datasets using visualizations
How Tableau Helps in Decision-Making:
Identifies trends and patterns quickly
Enables interactive dashboards for exploration
Improves forecasting and planning
Helps monitor KPIs in real time
Supports faster and smarter business decisions
Example:

A retail company can use Tableau dashboards to track sales performance across regions and identify low-performing products.

Question 2: Explain the role of the following Tableau components:
Answer:
a) Data Pane

The Data Pane contains all dimensions, measures, and data fields connected to the dataset.

Purpose:
Organizes data fields
Allows drag-and-drop visualization creation
Example:

Country, Sales, Profit fields appear in the Data Pane.

b) Worksheet

A Worksheet is a single visualization or chart area where users create graphs and analysis.

Purpose:
Build charts and graphs
Perform detailed analysis
Example:

Creating a bar chart of Sales by Country.

c) Dashboard

A Dashboard combines multiple worksheets into one interactive screen.

Purpose:
Provides complete business overview
Allows interactive filtering
Example:

Sales dashboard with maps, KPIs, and charts.

d) Story

A Story is a sequence of dashboards or worksheets used to present insights step-by-step.

Purpose:
Explains business insights narratively
Helps presentations and reporting
Example:

Showing quarterly sales growth story.

Question 3: What is the difference between Dimensions and Measures in Tableau? Provide examples of each.
Answer:
Feature	Dimensions	Measures
Definition	Qualitative fields	Quantitative fields
Nature	Categorical	Numerical
Aggregation	Cannot be aggregated directly	Can be aggregated
Usage	Used for grouping	Used for calculations
Example	Country, Product, Segment	Sales, Profit, Quantity
Dimensions Examples:
Country
Product Name
Region
Measures Examples:
Gross Sales
Profit
Units Sold
Example:

“Country” divides data into groups while “Sales” calculates total revenue.

Question 4: Define and explain the purpose of Filters, Parameters, and Sets in Tableau.
Answer:
Feature	Definition	Purpose
Filters	Restrict displayed data	Focus on specific information
Parameters	Dynamic user inputs	Interactive analysis
Sets	Custom subset of data	Group and compare data
Filters

Filters display only selected data.

Example:

Show sales only for India.

Parameters

Parameters allow users to dynamically change values.

Example:

Switch between Profit and Sales metrics.

Sets

Sets create custom groups of members.

Example:

Top 10 products by revenue.
"""



from IPython.display import Image
Image(filename='/content/Gemini_Generated_Image_czb05jczb05jczb0.png')